### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by camilochys** [Valoneu/TimberbornMods#1]
Hello! I don't know if I am doing anything wrong it just doesn't work, could you help me, please? :) I have tried a lot of stuff and I ended up deleting everything and re-installing the mod, lol.
I downloaded Specification one and Code one but none worked.
I am playing on Timberborn v0.2.9.1 and mod v1.0.3.0 (Manual Download from Thunderstore.io).
Thanks!

**Comment by Valoneu** [comment]
Im not sure how manual download works but it should work through mod manager sry cant help with manual downloading you will need to ask  some people on the discord.

**Comment by camilochys** [comment]
I downloaded it from Mod Manager! I will test it now!

**Comment by camilochys** [comment]
How does config and specification works, btw? I don't quite understand, thanks for answering btw!

**Comment by camilochys** [comment]
Works perfect (or at least I see the %, I don't know yet if they actually improve, I asume it's fine).
I just had to install it and configure it using Mod Manager, thanks for everything.

**Comment by Valoneu** [comment]
nice!
